name: Run METAR Script Every 15 Hours

# Controls when the action will run
on:
  schedule:
    # Run the script every 15 hours
    - cron: "0 */15 * * *"
  workflow_dispatch: # Allows manual triggering
    inputs:
      reason:
        description: 'Reason for manually triggering the workflow'
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies from requirements.txt
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run your Python script
    - name: Run METAR Script
      run: |
        python src/awc_api_mongo_upload.py
